export const weatherData = [
  {
    city: "Denpasar, Bali",
    date: "29/05/2025",
    day: "Thursday",
    windSpeed: "10 km/h",
    rainChance: "40%",
    temp: "30°",
    description: "Hujan Deras",
  },
  {
    city: "Denpasar, Bali",
    date: "30/05/2025",
    day: "Friday",
    windSpeed: "12 km/h",
    rainChance: "30%",
    temp: "31°",
    description: "Cerah Berawan",
  },
  {
    city: "Denpasar, Bali",
    date: "31/05/2025",
    day: "Saturday",
    windSpeed: "8 km/h",
    rainChance: "20%",
    temp: "32°",
    description: "Cerah",
  },
  {
    city: "Denpasar, Bali",
    date: "01/06/2025",
    day: "Sunday",
    windSpeed: "15 km/h",
    rainChance: "50%",
    temp: "29°",
    description: "Hujan Ringan",
  },
  {
    city: "Denpasar, Bali",
    date: "02/06/2025",
    day: "Monday",
    windSpeed: "10 km/h",
    rainChance: "60%",
    temp: "28°",
    description: "Hujan Deras",
  },
  {
    city: "Denpasar, Bali",
    date: "03/06/2025",
    day: "Tuesday",
    windSpeed: "12 km/h",
    rainChance: "40%",
    temp: "30°",
    description: "Hujan Petir",
  },
  {
    city: "Denpasar, Bali",
    date: "04/06/2025",
    day: "Wednesday",
    windSpeed: "10 km/h",
    rainChance: "30%",
    temp: "31°",
    description: "Cerah",
  },
  {
    city: "Denpasar, Bali",
    date: "05/06/2025",
    day: "Thursday",
    windSpeed: "8 km/h",
    rainChance: "10%",
    temp: "32°",
    description: "Cerah Berawan",
  },
  {
    city: "Denpasar, Bali",
    date: "06/06/2025",
    day: "Friday",
    windSpeed: "15 km/h",
    rainChance: "50%",
    temp: "29°",
    description: "Hujan Ringan",
  },
  {
    city: "Denpasar, Bali",
    date: "07/06/2025",
    day: "Saturday",
    windSpeed: "12 km/h",
    rainChance: "20%",
    temp: "30°",
    description: "Cerah",
  },
  {
    city: "Denpasar, Bali",
    date: "08/06/2025",
    day: "Sunday",
    windSpeed: "10 km/h",
    rainChance: "40%",
    temp: "30°",
    description: "Hujan Deras",
  },
  {
    city: "Denpasar, Bali",
    date: "09/06/2025",
    day: "Monday",
    windSpeed: "8 km/h",
    rainChance: "15%",
    temp: "31°",
    description: "Cerah Berawan",
  },
  {
    city: "Denpasar, Bali",
    date: "10/06/2025",
    day: "Tuesday",
    windSpeed: "14 km/h",
    rainChance: "55%",
    temp: "28°",
    description: "Hujan Petir",
  },
  {
    city: "Denpasar, Bali",
    date: "11/06/2025",
    day: "Wednesday",
    windSpeed: "10 km/h",
    rainChance: "35%",
    temp: "29°",
    description: "Hujan Ringan",
  },
  {
    city: "Denpasar, Bali",
    date: "12/06/2025",
    day: "Thursday",
    windSpeed: "9 km/h",
    rainChance: "20%",
    temp: "31°",
    description: "Cerah",
  },
  {
    city: "Denpasar, Bali",
    date: "13/06/2025",
    day: "Friday",
    windSpeed: "13 km/h",
    rainChance: "45%",
    temp: "29°",
    description: "Hujan Deras",
  },
  {
    city: "Denpasar, Bali",
    date: "14/06/2025",
    day: "Saturday",
    windSpeed: "10 km/h",
    rainChance: "30%",
    temp: "30°",
    description: "Cerah Berawan",
  },
  {
    city: "Denpasar, Bali",
    date: "15/06/2025",
    day: "Sunday",
    windSpeed: "8 km/h",
    rainChance: "10%",
    temp: "32°",
    description: "Cerah",
  },
];
