export const itemWisata = [
  
  {
    image: "https://plus.unsplash.com/premium_photo-1728117267325-534ccbd21a5f?q=80&w=2068&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Pantai Sanur",
    description: "Nikmati suasana pantai yang tenang di Pantai Sanur, cocok untuk bersantai dan menikmati sunrise.",
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
    lokasi: "Jl. Ayam GoRepoForked No.12"
  },
  {
    image: "https://media.istockphoto.com/id/1369703250/id/foto/bangunan-utama-pura-jagatnatha-bali-pada-siang-hari-berawan-diambil-pada-januari-2022.jpg?s=1024x1024&w=is&k=20&c=gwdfYW1bK2_1QaQ_U2jmGS3ofl8Pbilvo1idk_uLRx0=",
    title: "Pura Jagatnatha",
    description: "Temukan keindahan dan kedamaian di Pura Jagatnatha, pura terbesar di Denpasar.",
    rating: 4,
    kategori: "Budaya",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum Bali",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 3,
    kategori: "Keluarga",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museu",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum denpasar",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Keluarga",
    cuaca: "Panas",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1728117267325-534ccbd21a5f?q=80&w=2068&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Pantai Sanur",
    description: "Nikmati suasana pantai yang tenang di Pantai Sanur, cocok untuk bersantai dan menikmati sunrise.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Pantai Sanur"),
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
  },
  {
    image: "https://media.istockphoto.com/id/1369703250/id/foto/bangunan-utama-pura-jagatnatha-bali-pada-siang-hari-berawan-diambil-pada-januari-2022.jpg?s=1024x1024&w=is&k=20&c=gwdfYW1bK2_1QaQ_U2jmGS3ofl8Pbilvo1idk_uLRx0=",
    title: "Pura Jagatnatha",
    description: "Temukan keindahan dan kedamaian di Pura Jagatnatha, pura terbesar di Denpasar.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Pura Jagatnatha"),
    rating: 4,
    kategori: "Budaya",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum Bali",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 3,
    kategori: "Keluarga",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museu",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum denpasar",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Keluarga",
    cuaca: "Panas",
    price: "Rp20.000"
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1728117267325-534ccbd21a5f?q=80&w=2068&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Pantai Sanur",
    description: "Nikmati suasana pantai yang tenang di Pantai Sanur, cocok untuk bersantai dan menikmati sunrise.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Pantai Sanur"),
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
  },
  {
    image: "https://media.istockphoto.com/id/1369703250/id/foto/bangunan-utama-pura-jagatnatha-bali-pada-siang-hari-berawan-diambil-pada-januari-2022.jpg?s=1024x1024&w=is&k=20&c=gwdfYW1bK2_1QaQ_U2jmGS3ofl8Pbilvo1idk_uLRx0=",
    title: "Pura Jagatnatha",
    description: "Temukan keindahan dan kedamaian di Pura Jagatnatha, pura terbesar di Denpasar.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Pura Jagatnatha"),
    rating: 4,
    kategori: "Budaya",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum Bali",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 3,
    kategori: "Keluarga",
    cuaca: "Dingin",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museu",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Alam",
    cuaca: "Panas",
  },
  {
    image: "https://plus.unsplash.com/premium_photo-1661923335239-29a8eb325f86?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Museum denpasar",
    description: "Jelajahi sejarah Bali di Museum Bali dengan koleksi seni dan budaya yang menarik.",
    buttonText: "Lihat Detail",
    onButtonClick: () => alert("Detail Museum Bali"),
    rating: 5,
    kategori: "Keluarga",
    cuaca: "Panas",
  },
  
  
];
